/**
 * This file materializes `~/.fold/config.schema.json` from the SAME `FoldConfig` Effect Schema that
 * decodes the file (D25) - so editor validation/completion is always version-matched to the installed
 * fold. Generation goes through `Schema.toJsonSchemaDocument` (draft 2020-12) and
 * `JsonSchema.toDocumentDraft07` (editor compat), then assembles a self-contained document with the
 * draft-07 `$schema` URI and inlined `definitions`.
 *
 * `configInit` writes the schema (always, to stay current) and a commented starter `config.jsonc` (only
 * when absent, never clobbering an existing config) - the `foldcode config init` primitive.
 */
import { join } from 'node:path'

import { JsonSchema, Effect, Schema } from 'effect'

import { fileSystemFor, type FsToolOptions } from '../Fs/DefaultFileSystem'
import { FoldConfig } from './ConfigSchema'
import { writeFoldInfo } from './FoldInfo'
import { defaultConfigPath, defaultFoldHome } from './Load'

/** The generated schema file path for a home directory. */
export const configSchemaPath = (foldHome?: string): string => join(foldHome ?? defaultFoldHome(), 'config.schema.json')

/** The `FoldConfig` JSON Schema as a self-contained draft-07 document object (ready to serialize). */
export const foldConfigJsonSchema = (): Record<string, unknown> => {
	const document = JsonSchema.toDocumentDraft07(Schema.toJsonSchemaDocument(FoldConfig))
	const hasDefinitions = Object.keys(document.definitions).length > 0

	return {
		$schema: JsonSchema.META_SCHEMA_URI_DRAFT_07,
		...document.schema,
		...(hasDefinitions ? { definitions: document.definitions } : {}),
	}
}

/** The generated schema serialized as JSON text (tab-indented, trailing newline). */
export const foldConfigJsonSchemaText = (): string => `${JSON.stringify(foldConfigJsonSchema(), null, '\t')}\n`

/** A commented starter `config.jsonc` referencing the generated schema. */
export const starterConfigJsonc = (): string =>
	`{
	// fold configuration. Generated by \`foldcode config init\`; edit freely.
	// The $schema reference powers editor validation and completion.
	"$schema": "./config.schema.json",

	// Provider connection profiles. Prefer apiKeyEnv (reads the key from an env var) over inline apiKey.
	// configuredModels exposes private/custom model ids in the interactive model picker without changing roles.
	// OAuth kinds need no key here; use \`foldcode auth codex|opencode|xai login\`.
	"providers": {
		"anthropic": {
			"kind": "anthropic",
			"apiKeyEnv": "ANTHROPIC_API_KEY"
		},
		"openai": {
			"kind": "openai-compat",
			"apiKeyEnv": "OPENAI_API_KEY",
			"configuredModels": []
		},
		"codex": {
			"kind": "codex"
		},
		"opencode": {
			"kind": "opencode"
		},
		"xai": {
			"kind": "xai"
		}
	},

	// Model roles bound to a provider (+ optional model). "smart" and "fast" are required;
	// "orchestrator" is optional and falls back to "smart". Omitting "model" uses the provider
	// defaults: codex/opencode → gpt-5.6-sol, xai → grok-4.5, anthropic → claude-opus-4-8.
	"roles": {
		// Default primary model for new sessions.
		"smart": { "provider": "codex", "model": "gpt-5.6-sol", "reasoning": "medium" },
		// An explicit model always wins over the provider default.
		"fast": { "provider": "anthropic", "model": "claude-haiku-4-5-20251001" },
		// No model: uses the codex default, gpt-5.6-sol.
		"orchestrator": { "provider": "codex", "reasoning": "high" }
	},

	// Named profiles selected with \`foldcode --profile <name>\`; the top-level "roles" stays the default.
	// A profile is a complete role map and may pin a mode ("rlm" here) - an explicit --mode still wins.
	// RLM mode always includes the RPI specialist subagents.
	"profiles": {
		// Everything-max claude preset driving the RLM orchestrator mode.
		"ultraclaude": {
			"mode": "rlm",
			"orchestrator": { "provider": "anthropic", "model": "claude-fable-5", "reasoning": "max" },
			"smart": { "provider": "anthropic", "model": "claude-opus-4-8", "reasoning": "max" },
			"fast": { "provider": "anthropic", "model": "claude-sonnet-5", "reasoning": "max" }
		},
		// Like ultraclaude, but the orchestrator runs on opus-4-8 instead of fable-5.
		"powerclaude": {
			"mode": "rlm",
			"orchestrator": { "provider": "anthropic", "model": "claude-opus-4-8", "reasoning": "max" },
			"smart": { "provider": "anthropic", "model": "claude-opus-4-8", "reasoning": "max" },
			"fast": { "provider": "anthropic", "model": "claude-sonnet-5", "reasoning": "max" }
		},
		// Everything-max codex preset driving the RLM orchestrator mode.
		"ultracodex": {
			"mode": "rlm",
			"orchestrator": { "provider": "codex", "model": "gpt-5.6-sol", "reasoning": "max" },
			"smart": { "provider": "codex", "model": "gpt-5.6-terra", "reasoning": "max" },
			"fast": { "provider": "codex", "model": "gpt-5.6-luna", "reasoning": "max" }
		}
	},

	// Auto-compaction is enabled by default. Optional knobs are thresholdTokens, contextWindow,
	// reserveTokens, keepRecentTokens, and compactionPrompt.
	"compaction": { "enabled": true },

	// Runtime stop conditions. The default product launch uses this doom-loop guard even when omitted.
	"stopConditions": {
		"doomLoop": { "enabled": true, "repeatedToolCalls": 3 }
	}
}
`

/** Options for {@link writeFoldConfigSchema} and {@link configInit}. */
export type ConfigInitOptions = {
	/** The fold home directory. Defaults to `~/.fold`. */
	readonly foldHome?: string
	/** FileSystem override for hermetic tests. Defaults to the Node platform filesystem. */
	readonly fileSystem?: FsToolOptions['fileSystem']
}

/** Write `config.schema.json` under the fold home, creating the directory if needed. Returns its path. */
export const writeFoldConfigSchema = (options?: ConfigInitOptions): Effect.Effect<string> =>
	Effect.gen(function* () {
		const fs = fileSystemFor(options?.fileSystem === undefined ? {} : { fileSystem: options.fileSystem })
		const home = options?.foldHome ?? defaultFoldHome()
		yield* fs.makeDirectory(home, { recursive: true }).pipe(Effect.orDie)

		const path = configSchemaPath(options?.foldHome)
		yield* fs.writeFileString(path, foldConfigJsonSchemaText()).pipe(Effect.orDie)
		return path
	})

/** Result of {@link bootstrapFoldHome} / {@link configInit}. */
export type ConfigInitResult = {
	readonly configPath: string
	readonly schemaPath: string
	/** Path of the generated FOLD_INFO.md guide (always rewritten). */
	readonly infoPath: string
	/** Path of the OAuth credential store (created EMPTY when absent; filled by `foldcode auth codex login`). */
	readonly authPath: string
	/** True when a starter `config.jsonc` was created; false when one already existed (left untouched). */
	readonly createdConfig: boolean
	/** True when an empty `auth.json` was created; false when one already existed (left untouched). */
	readonly createdAuth: boolean
}

/**
 * Bootstrap the fold home. Runs on EVERY CLI session start (synchronously, before the config loads)
 * and behind `foldcode config init`: create the directory, (re)write the version-matched
 * `config.schema.json` and `FOLD_INFO.md`, write the commented starter `config.jsonc` only when none
 * exists, and create an EMPTY provider-keyed `auth.json` (mode 0600) only when none exists - a first
 * run lands a working layout with providers configured but credential-less until
 * `foldcode auth codex login` runs or the `apiKeyEnv` variables are exported. Only the two generated
 * files are ever overwritten.
 */
export const bootstrapFoldHome = (options?: ConfigInitOptions): Effect.Effect<ConfigInitResult> =>
	Effect.gen(function* () {
		const fs = fileSystemFor(options?.fileSystem === undefined ? {} : { fileSystem: options.fileSystem })
		const schemaPath = yield* writeFoldConfigSchema(options)
		const infoPath = yield* writeFoldInfo(options)

		const configPath = defaultConfigPath(options?.foldHome)
		const configExists = yield* fs.exists(configPath).pipe(Effect.catch(() => Effect.succeed(false)))
		if (!configExists) {
			yield* fs.writeFileString(configPath, starterConfigJsonc()).pipe(Effect.orDie)
		}

		const authPath = join(options?.foldHome ?? defaultFoldHome(), 'auth.json')
		const authExists = yield* fs.exists(authPath).pipe(Effect.catch(() => Effect.succeed(false)))
		if (!authExists) {
			// Same document shape and permissions the codex auth store maintains (provider-keyed JSON).
			yield* fs.writeFileString(authPath, '{}\n', { mode: 0o600 }).pipe(Effect.orDie)
			yield* fs.chmod(authPath, 0o600).pipe(Effect.catch(() => Effect.void))
		}

		return { configPath, schemaPath, infoPath, authPath, createdConfig: !configExists, createdAuth: !authExists }
	})

/** `foldcode config init`: the same bootstrap, kept under its command-facing name. */
export const configInit = (options?: ConfigInitOptions): Effect.Effect<ConfigInitResult> => bootstrapFoldHome(options)
