/**
 * This file materializes `~/.tart/config.schema.json` from the SAME `TartConfig` Effect Schema that
 * decodes the file (D25) - so editor validation/completion is always version-matched to the installed
 * tart. Generation goes through `Schema.toJsonSchemaDocument` (draft 2020-12) and
 * `JsonSchema.toDocumentDraft07` (editor compat), then assembles a self-contained document with the
 * draft-07 `$schema` URI and inlined `definitions`.
 *
 * `configInit` writes the schema (always, to stay current) and a commented starter `config.jsonc` (only
 * when absent, never clobbering an existing config) - the `tart config init` primitive.
 */
import { join } from 'node:path'

import { JsonSchema, Effect, Schema } from 'effect'

import { fileSystemFor, type FsToolOptions } from '../Fs/DefaultFileSystem'
import { TartConfig } from './ConfigSchema'
import { defaultConfigPath, defaultTartHome } from './Load'

/** The generated schema file path for a home directory. */
export const configSchemaPath = (tartHome?: string): string => join(tartHome ?? defaultTartHome(), 'config.schema.json')

/** The `TartConfig` JSON Schema as a self-contained draft-07 document object (ready to serialize). */
export const tartConfigJsonSchema = (): Record<string, unknown> => {
	const document = JsonSchema.toDocumentDraft07(Schema.toJsonSchemaDocument(TartConfig))
	const hasDefinitions = Object.keys(document.definitions).length > 0

	return {
		$schema: JsonSchema.META_SCHEMA_URI_DRAFT_07,
		...document.schema,
		...(hasDefinitions ? { definitions: document.definitions } : {}),
	}
}

/** The generated schema serialized as JSON text (tab-indented, trailing newline). */
export const tartConfigJsonSchemaText = (): string => `${JSON.stringify(tartConfigJsonSchema(), null, '\t')}\n`

/** A commented starter `config.jsonc` referencing the generated schema. */
export const starterConfigJsonc = (): string =>
	`{
	// tart configuration. Generated by \`tart config init\`; edit freely.
	// The $schema reference powers editor validation and completion.
	"$schema": "./config.schema.json",

	// Provider connection profiles. Prefer apiKeyEnv (reads the key from an env var) over inline apiKey.
	// The codex kind needs no key here - it uses ~/.tart/auth.json (run \`tart auth codex login\`).
	"providers": {
		"anthropic": {
			"kind": "anthropic",
			"apiKeyEnv": "ANTHROPIC_API_KEY"
		},
		"openai": {
			"kind": "openai-compat",
			"apiKeyEnv": "OPENAI_API_KEY"
		},
		"codex": {
			"kind": "codex"
		}
	},

	// Model roles bound to a provider + model. "smart" and "fast" are required; "orchestrator" is
	// optional and falls back to "smart".
	"roles": {
		"smart": { "provider": "anthropic", "model": "claude-opus-4-8", "reasoning": "medium" },
		"fast": { "provider": "anthropic", "model": "claude-haiku-4-5-20251001" }
	},

	// Auto-compaction is disabled by default. Set enabled=true to summarize old history near the
	// context limit; optional knobs are contextWindow, reserveTokens, keepRecentTokens, compactionPrompt.
	"compaction": { "enabled": false },

	// Runtime stop conditions. The default product launch uses this doom-loop guard even when omitted.
	"stopConditions": {
		"doomLoop": { "enabled": true, "repeatedToolCalls": 3 }
	}
}
`

/** Options for {@link writeTartConfigSchema} and {@link configInit}. */
export type ConfigInitOptions = {
	/** The tart home directory. Defaults to `~/.tart`. */
	readonly tartHome?: string
	/** FileSystem override for hermetic tests. Defaults to the Node platform filesystem. */
	readonly fileSystem?: FsToolOptions['fileSystem']
}

/** Write `config.schema.json` under the tart home, creating the directory if needed. Returns its path. */
export const writeTartConfigSchema = (options?: ConfigInitOptions): Effect.Effect<string> =>
	Effect.gen(function* () {
		const fs = fileSystemFor(options?.fileSystem === undefined ? {} : { fileSystem: options.fileSystem })
		const home = options?.tartHome ?? defaultTartHome()
		yield* fs.makeDirectory(home, { recursive: true }).pipe(Effect.orDie)

		const path = configSchemaPath(options?.tartHome)
		yield* fs.writeFileString(path, tartConfigJsonSchemaText()).pipe(Effect.orDie)
		return path
	})

/** Result of {@link configInit}. */
export type ConfigInitResult = {
	readonly configPath: string
	readonly schemaPath: string
	/** True when a starter `config.jsonc` was created; false when one already existed (left untouched). */
	readonly createdConfig: boolean
}

/**
 * Initialize the tart config directory (`tart config init`): (re)write the version-matched
 * `config.schema.json` and, only when no `config.jsonc` exists yet, write a commented starter. An
 * existing config is never overwritten.
 */
export const configInit = (options?: ConfigInitOptions): Effect.Effect<ConfigInitResult> =>
	Effect.gen(function* () {
		const fs = fileSystemFor(options?.fileSystem === undefined ? {} : { fileSystem: options.fileSystem })
		const schemaPath = yield* writeTartConfigSchema(options)

		const configPath = defaultConfigPath(options?.tartHome)
		const exists = yield* fs.exists(configPath).pipe(Effect.catch(() => Effect.succeed(false)))
		if (!exists) {
			yield* fs.writeFileString(configPath, starterConfigJsonc()).pipe(Effect.orDie)
		}

		return { configPath, schemaPath, createdConfig: !exists }
	})
