/**
 * This file owns `<tartHome>/TART_INFO.md` - the generated, version-matched guide to configuring and
 * using tart. It is written by `tart config init` and refreshed before every session open,
 * and every session's leading prompt carries its path (Mode/Launch `tartInfoBlock`), so the agent can
 * read it to answer configuration questions and edit `config.jsonc` on the user's behalf.
 *
 * The content lives here as a const (not a data file - packages run TypeScript directly) and must stay
 * accurate to the shipped behavior; it is the in-product companion to the design docs.
 */
import { join } from 'node:path'

import { Effect } from 'effect'

import { fileSystemFor } from '../Fs/DefaultFileSystem'
import type { ConfigInitOptions } from './ConfigSchemaJson'
import { defaultTartHome } from './Load'

/** The generated guide's path for a tart home. */
export const tartInfoPath = (tartHome?: string): string => join(tartHome ?? defaultTartHome(), 'TART_INFO.md')

/** The full TART_INFO.md content. Regenerated on config init and CLI startup (always overwritten). */
export const TART_INFO_MD: string = `# Tart - configuration and CLI guide

> Generated by tart; refreshed automatically on every CLI start. Edits here are overwritten - change
> \`config.jsonc\` (same directory) to configure tart. This file exists so the agent you are talking to
> can answer questions about tart and reconfigure it for you: ask it things like "switch me to the
> ultracodex profile" or "add an openrouter provider", and it can edit \`config.jsonc\` directly.
> Config changes bind on the NEXT launch or resume, not mid-session.
> Source code: https://github.com/humanlayer/tart

## The config file

\`~/.tart/config.jsonc\` (JSONC: comments and trailing commas allowed). Every CLI session start
bootstraps the whole layout: it creates \`~/.tart\` if needed, writes the starter config when none
exists (never overwriting yours), creates an EMPTY \`auth.json\` (mode 0600 - credential-less until
\`tart auth codex login\` runs or your \`apiKeyEnv\` variables are exported), and refreshes the
generated \`config.schema.json\` + this guide so both always match the installed tart.
\`tart config init\` runs the same bootstrap explicitly; \`tart config validate\` decodes and
cross-checks the file. Unknown top-level keys are rejected.

## Providers

Named connections under \`providers\`; roles and profiles reference these keys.

\`\`\`jsonc
"providers": {
  "anthropic": { "kind": "anthropic", "apiKeyEnv": "ANTHROPIC_API_KEY" },
  "openai":    { "kind": "openai-compat", "apiKeyEnv": "OPENAI_API_KEY" }, // baseUrl optional
  "codex":     { "kind": "codex" } // no key: uses ~/.tart/auth.json (tart auth codex login)
}
\`\`\`

- \`kind\`: \`anthropic\` | \`openai-compat\` | \`codex\`.
- Prefer \`apiKeyEnv\` over inline \`apiKey\`. Codex authenticates via stored OAuth
  (\`tart auth codex login|status|logout\`).

## Roles - the default model map

\`roles\` binds the three model roles tart uses. \`smart\` and \`fast\` are required; \`orchestrator\`
is optional and falls back to \`smart\`.

| Role | Used by |
|---|---|
| \`smart\` | default mode's primary agent; \`general-purpose\` subagent; RPI implementers |
| \`fast\` | \`researcher\` and \`bash\` subagents; RPI research/review agents |
| \`orchestrator\` | the RLM mode's primary agent |

Each binding is \`{ "provider": <key>, "model"?: <id>, "reasoning"?: <level> }\`. Omitting \`model\`
uses the provider kind's default: codex → \`gpt-5.6-sol\`, anthropic → \`claude-opus-4-8\`
(openai-compat requires an explicit model). \`reasoning\` is one of \`off · minimal · low · medium ·
high · xhigh · max\` and is validated against the model catalog - a level the model does not support
fails the launch naming the supported levels. All roles referenced by a launch resolve eagerly, so
every binding needs working credentials.

## Profiles - named presets (roles + optional mode)

\`profiles\` holds named role maps selected with \`--profile <name>\`; the top-level \`roles\` stays
the default. A profile may also pin a \`mode\` - an explicit \`--mode\` flag still wins. Tart ships
three RLM presets in the starter config (RLM always includes the RPI specialist subagents):

\`\`\`jsonc
"profiles": {
  "ultraclaude": {
    "mode": "rlm",
    "orchestrator": { "provider": "anthropic", "model": "claude-fable-5", "reasoning": "max" },
    "smart":        { "provider": "anthropic", "model": "claude-opus-4-8", "reasoning": "max" },
    "fast":         { "provider": "anthropic", "model": "claude-sonnet-5", "reasoning": "max" }
  },
  "powerclaude": { // like ultraclaude, with the orchestrator on opus-4-8 instead of fable-5
    "mode": "rlm",
    "orchestrator": { "provider": "anthropic", "model": "claude-opus-4-8", "reasoning": "max" },
    "smart":        { "provider": "anthropic", "model": "claude-opus-4-8", "reasoning": "max" },
    "fast":         { "provider": "anthropic", "model": "claude-sonnet-5", "reasoning": "max" }
  },
  "ultracodex": {
    "mode": "rlm",
    "orchestrator": { "provider": "codex", "model": "gpt-5.6-sol",   "reasoning": "max" },
    "smart":        { "provider": "codex", "model": "gpt-5.6-terra", "reasoning": "max" },
    "fast":         { "provider": "codex", "model": "gpt-5.6-luna",  "reasoning": "max" }
  }
}
\`\`\`

\`tart --profile ultraclaude\` therefore runs the RLM orchestrator on claude-fable-5 at max reasoning,
with opus-4-8/sonnet-5 (both max) behind the smart/fast roles. Model-override flags
(\`--role/--provider/--model/--reasoning\`) apply on top of the selected profile's roles.

Inside a session, the SDK can rebind one role live (\`session.setProfile(role, model)\`): running
subagents finish on their current model, the next dispatch uses the new binding, and resuming a
pre-switch subagent writes a durable model-change transition.

## Modes and --rpi

- \`--mode default\` - full coding toolset (read/write/edit/apply_patch/bash + skills + subagents).
- \`--mode rlm\` - orchestrator preset: NO bash on the primary agent, a strong delegation prompt, and
  the subagent roster to route work through. Runs on the \`orchestrator\` role and ALWAYS includes
  the RPI specialists.
- \`--rpi\` - adds the seven RPI specialist subagents (codebase-locator/analyzer/pattern-finder,
  implementation-reviewer, implementer-agent, outline-implementer-agent, web-search-researcher) to
  the DEFAULT mode's roster (RLM already carries them).

Which role each agent runs on: primary = the mode's role (\`smart\` for default, \`orchestrator\` for
rlm, or \`--role\`); \`general-purpose\`, \`implementer-agent\`, and \`outline-implementer-agent\` =
\`smart\`; \`researcher\`, \`bash\`, and the RPI research/review agents (codebase-locator/analyzer/
pattern-finder, implementation-reviewer, web-search-researcher) = \`fast\`.

## CLI quick reference

\`\`\`
tart                             # interactive session (default mode, smart role)
tart --prompt "..."              # one-shot run; exit codes 0/130/1
tart --profile ultracodex        # profile's roles + its pinned mode (rlm)
tart --mode rlm --rpi            # explicit mode + RPI roster
tart --role fast --reasoning off # primary on the fast role, reasoning off
tart --provider codex            # kind change drops the stale model -> gpt-5.6-sol default
tart --resume latest|sess_*      # resume (config re-resolves; drift writes a durable transition)
tart sessions                    # list this project's session logs
tart config init|validate        # starter config + schema | validate
tart auth codex login|status|logout
tart bin status|install          # managed binaries: rg, fd, ast-grep
\`\`\`

Interactive commands: plain text sends (or steers the running root agent); \`/steer <agent_id> <text>\`
and \`/send <agent_id> <text>\` target subagents (4+ id characters from the output tags work);
\`/stop [reason]\` stops gracefully at the next batch boundary; \`/help\`; \`/exit\`.

## Where tart lives on disk

| Path | What it is |
|---|---|
| \`~/.tart/config.jsonc\` | your configuration (with generated \`config.schema.json\` and \`TART_INFO.md\` beside it) |
| \`~/.tart/sessions/<project-slug>/<sess_id>.jsonl\` | one durable event log per session, grouped per project |
| \`~/.tart/auth.json\` | OAuth credentials (codex), mode 0600 - created EMPTY on first run; fill via \`tart auth codex login\` |
| \`~/.tart/bin/\` | managed binaries (rg, fd, ast-grep); prepended to every bash command's PATH |
| \`~/.tart/cache/\` | model-catalog cache (\`models-dev.json\`, 24h TTL) |
| \`~/.tart/skills/\` | global skills (one \`SKILL.md\` directory per skill), scanned with the repo/cwd \`.agents/skills\` |
| \`~/.tart/AGENTS.md\` | global agent memory (first existing of \`~/.tart\` → \`~/.agents\` → \`~/.codex\` wins) |

The \`<project-slug>\` is the working directory's path with separators escaped, so each project's
sessions sit in their own directory and \`--resume latest\` means "newest for THIS project".

## Sessions and the event log

A session IS its log: one append-only JSONL file (one JSON event per line). Everything else - the
messages sent to the model, per-tool state, token usage, the subagent registry - is a projection
folded over that log, so resuming a session is just replaying the file (\`--resume latest\` or
\`--resume sess_...\`; \`tart sessions\` prints ids, timestamps, and paths, and the session header
prints the exact log path). Nothing derived is stored; if it happened, it is on disk (write-through).

Every entry carries the same envelope, then a type-specific payload:

- \`seq\` - canonical total order; \`ts\` - epoch milliseconds
- \`agentId\` / \`parentAgentId\` - which agent wrote the entry. Subagents are FLAT, keyed by id
  (never nested): every agent in a session appends to the same one file
- \`toolCallId\` - groups a subagent's entries under the tool call that dispatched (or resumed) it
- \`_tag\` - the entry type: \`session_started\`, \`agent_started\`, \`system-message\`,
  \`user-message\`, \`assistant-message\` (carries the response's token usage), \`tool-result\`,
  \`tool_state\`, \`compaction\`, \`model-change\`, \`thinking-change\`, \`tools-change\`,
  \`agent-finished\`, \`error\`

The file is plain text, so \`rg\` over it works and is the intended recovery path: after
auto-compaction the replaced history STAYS in the log (only the projection cuts it), and the agent is
told to search it narrowly - filter lines by exact file paths, error snippets, tool names, or user
wording - rather than re-reading it wholesale. In RLM mode (no bash on the orchestrator), that search
is delegated to the \`bash\` subagent.

## Managed binaries

Tart ensures \`rg\` (ripgrep), \`fd\`, and \`ast-grep\` are available - system binaries first, else
sha256-verified downloads into \`~/.tart/bin\` (which bash commands have on PATH). \`ast-grep outline
<file-or-dir>\` prints a structural table of contents; agents are prompted to prefer \`rg\` over grep
and \`fd\` over find. Disable downloads with \`TART_DISABLE_BINARY_DOWNLOADS=1\`.

## Troubleshooting

- \`RoleResolutionError: env var ... is not set\` - export the binding's \`apiKeyEnv\`.
- \`RoleResolutionError\` naming reasoning levels - pick a supported level (or \`off\`).
- \`UnknownProfileError\` - the \`--profile\` name is not under \`profiles\`; it lists what exists.
- A launch fails for a role you did not select - all referenced roles resolve eagerly; point unused
  roles at providers you have credentials for.
- Stale model metadata - the catalog refreshes from models.dev on launch (24h cache under
  \`~/.tart/cache/\`); pin with \`TART_DISABLE_MODELS_FETCH=1\`.
`

/** Write (always overwrite) `<tartHome>/TART_INFO.md`, creating the directory if needed. Returns its path. */
export const writeTartInfo = (options?: ConfigInitOptions): Effect.Effect<string> =>
	Effect.gen(function* () {
		const fs = fileSystemFor(options?.fileSystem === undefined ? {} : { fileSystem: options.fileSystem })
		const home = options?.tartHome ?? defaultTartHome()
		yield* fs.makeDirectory(home, { recursive: true }).pipe(Effect.orDie)
		const path = tartInfoPath(home)
		yield* fs.writeFileString(path, TART_INFO_MD).pipe(Effect.orDie)

		return path
	})
