/**
 * Regenerates `src/Catalog/BakedCatalog.ts` - the baked models.dev snapshot for the `anthropic` and
 * `openai` providers, already normalized to core `ModelCatalogEntry` rows. Reads a local snapshot
 * from `/tmp/models_dev_api.json` when present (avoid hammering models.dev while iterating),
 * otherwise fetches `https://models.dev/api.json` fresh.
 *
 * Usage: `bun packages/fold-agent/scripts/update-model-catalog.ts`
 */
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { ModelCatalogEntry, ModelPricing } from '@humanlayer/fold-core'
import { Effect, Schema } from 'effect'

import { decodeModelsDevModels } from '../src/Catalog/ModelsDevSchema'
import { modelCatalogEntriesFromModelsDev } from '../src/Catalog/Normalize'

const SNAPSHOT_PATH = '/tmp/models_dev_api.json'
const MODELS_DEV_URL = 'https://models.dev/api.json'
const BAKED_PROVIDERS: ReadonlySet<string> = new Set(['anthropic', 'openai'])

const scriptDir = dirname(fileURLToPath(import.meta.url))
const targetPath = join(scriptDir, '..', 'src', 'Catalog', 'BakedCatalog.ts')

/** The bake could not read, decode, or normalize a usable snapshot. */
class CatalogBakeError extends Schema.TaggedErrorClass<CatalogBakeError>()('CatalogBakeError', {
	message: Schema.String,
}) {}

/** The raw payload: the local snapshot when present, a fresh fetch otherwise. */
const readPayload: Effect.Effect<unknown, CatalogBakeError> = Effect.suspend(() => {
	if (existsSync(SNAPSHOT_PATH)) {
		return Effect.try({
			try: (): unknown => JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf8')),
			catch: (cause) => new CatalogBakeError({ message: `could not parse ${SNAPSHOT_PATH}: ${String(cause)}` }),
		}).pipe(Effect.tap(() => Effect.log(`using local snapshot ${SNAPSHOT_PATH}`)))
	}

	return Effect.tryPromise({
		try: async (signal): Promise<unknown> => {
			const response = await fetch(MODELS_DEV_URL, { signal })
			if (!response.ok) throw new Error(`GET ${MODELS_DEV_URL} responded ${response.status}`)
			const body: unknown = await response.json()
			return body
		},
		catch: (cause) => new CatalogBakeError({ message: `could not fetch ${MODELS_DEV_URL}: ${String(cause)}` }),
	}).pipe(Effect.tap(() => Effect.log(`fetched ${MODELS_DEV_URL}`)))
})

const stringLiteral = (value: string): string => `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`

const nullableString = (value: string | null): string => (value === null ? 'null' : stringLiteral(value))

const nullableNumber = (value: number | null): string => (value === null ? 'null' : String(value))

const effortsLiteral = (efforts: ReadonlyArray<string> | null): string =>
	efforts === null ? 'null' : `[${efforts.map(stringLiteral).join(', ')}]`

const pricingLiteral = (pricing: ModelPricing | null): string =>
	pricing === null
		? 'null'
		: `{ inputPerMTokens: ${pricing.inputPerMTokens}, outputPerMTokens: ${pricing.outputPerMTokens}, ` +
			`cacheReadPerMTokens: ${nullableNumber(pricing.cacheReadPerMTokens)}, ` +
			`cacheWritePerMTokens: ${nullableNumber(pricing.cacheWritePerMTokens)} }`

const entrySource = (entry: ModelCatalogEntry): string =>
	[
		'\t{',
		`\t\tproviderId: ${stringLiteral(entry.providerId)},`,
		`\t\tmodelId: ${stringLiteral(entry.modelId)},`,
		`\t\tname: ${nullableString(entry.name)},`,
		`\t\tcontextWindow: ${entry.contextWindow},`,
		`\t\tmaxInputTokens: ${nullableNumber(entry.maxInputTokens)},`,
		`\t\tmaxOutputTokens: ${entry.maxOutputTokens},`,
		`\t\treasoning: ${entry.reasoning},`,
		`\t\treasoningEfforts: ${effortsLiteral(entry.reasoningEfforts)},`,
		`\t\tvision: ${entry.vision},`,
		`\t\ttoolCall: ${entry.toolCall},`,
		`\t\tpricing: ${pricingLiteral(entry.pricing)},`,
		'\t},',
	].join('\n')

const fileSource = (entries: ReadonlyArray<ModelCatalogEntry>): string =>
	[
		'// GENERATED by scripts/update-model-catalog.ts - do not edit by hand.',
		'// Baked models.dev snapshot for the anthropic and openai providers, normalized to ModelCatalogEntry.',
		'// Regenerate: bun packages/fold-agent/scripts/update-model-catalog.ts',
		"import type { ModelCatalogEntry } from '@humanlayer/fold-core'",
		'',
		'/**',
		' * The offline model catalog: the last-resort fallback when neither a cached nor a freshly fetched',
		' * models.dev catalog is available (D15). Covers every anthropic and openai model models.dev knew',
		' * at generation time.',
		' */',
		'export const bakedModelCatalog: ReadonlyArray<ModelCatalogEntry> = [',
		...entries.map(entrySource),
		']',
		'',
	].join('\n')

const main = Effect.gen(function* () {
	const payload = yield* readPayload
	const models = yield* decodeModelsDevModels(payload)
	const baked = models.filter((named) => BAKED_PROVIDERS.has(named.providerId))
	const entries = [...modelCatalogEntriesFromModelsDev(baked)].sort((left, right) =>
		left.providerId === right.providerId
			? left.modelId.localeCompare(right.modelId)
			: left.providerId.localeCompare(right.providerId),
	)

	if (entries.length === 0) {
		return yield* new CatalogBakeError({
			message: 'no anthropic/openai entries survived normalization; refusing to bake',
		})
	}

	yield* Effect.sync(() => writeFileSync(targetPath, fileSource(entries)))

	// Best-effort formatting so the generated file matches the repo style byte-for-byte.
	yield* Effect.sync(() => spawnSync('bunx', ['oxfmt', targetPath], { stdio: 'ignore' }))

	yield* Effect.log(`wrote ${entries.length} entries to ${targetPath}`)
})

void Effect.runPromise(main).catch((error: unknown) => {
	console.error(error)
	process.exitCode = 1
})
