/**
 * Regenerates `src/Bin/BinaryChecksums.ts` - the pinned sha256 digests for every managed-binary
 * release asset in the registry (D18: opencode's lazy download pattern, plus the checksum pinning
 * opencode lacks). Downloads each pinned asset for every supported platform and hashes it, so run
 * this after changing any pin in `src/Bin/Registry.ts`.
 *
 * Usage: `bun packages/fold-agent/scripts/update-managed-binaries.ts`
 */
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { Effect, Schema } from 'effect'

import { MANAGED_BINARY_PLATFORMS, managedBinaryRegistry } from '../src/Bin/Registry'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const targetPath = join(scriptDir, '..', 'src', 'Bin', 'BinaryChecksums.ts')
const downloadTimeoutMillis = 180_000

/** One pinned asset could not be downloaded, so its digest cannot be regenerated. */
class ChecksumBakeError extends Schema.TaggedErrorClass<ChecksumBakeError>()('ChecksumBakeError', {
	message: Schema.String,
}) {}

const fetchBytes = (url: string): Effect.Effect<Uint8Array, ChecksumBakeError> =>
	Effect.tryPromise({
		try: async (signal): Promise<Uint8Array> => {
			const response = await fetch(url, { signal })
			if (!response.ok) throw new Error(`responded ${response.status}`)
			return new Uint8Array(await response.arrayBuffer())
		},
		catch: (cause) =>
			new ChecksumBakeError({ message: `GET ${url}: ${cause instanceof Error ? cause.message : String(cause)}` }),
	}).pipe(
		Effect.timeout(downloadTimeoutMillis),
		Effect.catchTag('TimeoutError', () =>
			Effect.fail(new ChecksumBakeError({ message: `GET ${url} timed out after ${downloadTimeoutMillis}ms` })),
		),
	)

/** Every pinned asset URL across the registry, in registry-then-platform order, deduplicated. */
const pinnedAssetUrls = (): ReadonlyArray<string> => {
	const urls: Array<string> = []
	for (const definition of managedBinaryRegistry) {
		for (const platformKey of MANAGED_BINARY_PLATFORMS) {
			const separator = platformKey.lastIndexOf('-')
			const platform = platformKey.slice(0, separator)
			const arch = platformKey.slice(separator + 1)
			const asset = definition.assetFor(platform, arch)
			if (asset !== null && !urls.includes(asset.url)) urls.push(asset.url)
		}
	}

	return urls
}

const renderChecksumsFile = (digests: ReadonlyArray<readonly [string, string]>): string => {
	const rows = digests.map(([url, digest]) => `\t'${url}': '${digest}',`).join('\n')

	return (
		'// GENERATED by scripts/update-managed-binaries.ts - do not edit by hand.\n' +
		'// sha256 hex digests of the pinned managed-binary release assets, keyed by download URL.\n' +
		'// Regenerate: bun packages/fold-agent/scripts/update-managed-binaries.ts\n' +
		'\n' +
		'/**\n' +
		" * Pinned sha256 digests for the registry's release assets (D18). An asset URL missing from this\n" +
		' * table reads as an unpinned asset: the download still happens, but verification is skipped.\n' +
		' */\n' +
		'export const managedBinaryChecksums: Readonly<Record<string, string>> = {\n' +
		`${rows}\n` +
		'}\n'
	)
}

const program = Effect.gen(function* () {
	const urls = pinnedAssetUrls()
	yield* Effect.log(`hashing ${urls.length} pinned assets`)

	const digests: Array<readonly [string, string]> = []
	const failures: Array<string> = []

	// Sequential on purpose: 15 multi-megabyte downloads in parallel just trip GitHub rate limiting.
	for (const url of urls) {
		const bytes = yield* fetchBytes(url).pipe(
			Effect.catch((error) =>
				Effect.logWarning(`SKIP ${url}: ${error.message}`).pipe(
					Effect.tap(() => Effect.sync(() => failures.push(`${url}: ${error.message}`))),
					Effect.as(null),
				),
			),
		)
		if (bytes === null) continue

		const digest = createHash('sha256').update(bytes).digest('hex')
		digests.push([url, digest])
		yield* Effect.log(`${digest}  ${url} (${(bytes.byteLength / 1024 / 1024).toFixed(1)}MB)`)
	}

	writeFileSync(targetPath, renderChecksumsFile(digests))
	spawnSync('bunx', ['oxfmt', targetPath], { stdio: 'inherit' })
	yield* Effect.log(`wrote ${digests.length} digests to ${targetPath}`)

	if (failures.length > 0) {
		yield* Effect.logWarning(
			`${failures.length} assets could not be hashed and stay UNPINNED (verification skipped at install):\n` +
				failures.join('\n'),
		)
	}
})

Effect.runPromise(program).catch((cause: unknown) => {
	console.error(cause)
	process.exitCode = 1
})
